name: 'Build Kernel Package'
description: 'Builds revpi kernel package'
inputs:
  changelog_author:
    description: 'name of changelog author'
    required: true
    default: 'Revolution Pi Development Team'
  changelog_author_email:
    description: 'email of changelog author'
    required: true
    default: 'development@revolutionpi.de'
  changelog_update:
    description: 'automatically update the changelog and version based on date and commit id'
    required: true
    default: "1"
  kernelbakery_branch:
    description: "branch to use from kernelbakery repository"
    required: true
    default: master
  picontrol_branch:
    description: "branch to use from piControl repository"
    required: true
    default: master
  build_commit:
    description: "SHA1 hash of the commit"
    required: false
outputs:
  filename_kernel:
    description: 'name of the kernel package'
  filename_headers:
    description: 'name of the kernel headers package'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code'
  color: 'orange'
