#!/bin/bash

set -x
set -e

export DEBIAN_FRONTEND=noninteractive
export LD_PRELOAD=libeatmydata.so
export LD_LIBRARY_PATH=/usr/lib/libeatmydata

BUILD_DIR=$GITHUB_WORKSPACE

echo $BUILD_DIR

(cd $BUILD_DIR/linux && ls && git rev-parse --abbrev-ref HEAD)
(cd $BUILD_DIR/piControl && ls && git rev-parse --abbrev-ref HEAD)
(cd $BUILD_DIR/kernelbakery && ls && git rev-parse --abbrev-ref HEAD)

if [[ ! -d "${BUILD_DIR}/kernelbakery" ]] || [[ ! -d "${BUILD_DIR}/piControl" ]] || [[ ! -d "${BUILD_DIR}/linux" ]] ; then
        >&2 echo "Missing required repos in ${BUILD_DIR}"
            ls ${BUILD_DIR}
            exit 1
fi

cd ${BUILD_DIR}/kernelbakery
LINUXDIR=${BUILD_DIR}/linux PIKERNELMODDIR=${BUILD_DIR}/piControl debian/update.sh

if [[ ${INPUT_CHANGELOG_UPDATE:-1} -eq 1 ]]; then
	BUILD_DATE=$(date "+%y%m%d%H%M%S")
	BUILD_COMMIT=$(cd ../linux && git rev-parse --short HEAD )

  NAME=${INPUT_CHANGELOG_AUTHOR} \
  EMAIL=${INPUT_CHANGELOG_AUTHOR_EMAIL} \
	debchange  -l "~${BUILD_DATE}-${BUILD_COMMIT}" -D experimental "this is an automatic build generated by the buildsystem"
fi

dpkg-buildpackage -a armhf -b -us -uc

FILENAME_KERNEL=$(basename ${BUILD_DIR}/raspberrypi-kernel_*.deb)
FILENAME_HEADERS=$(basename ${BUILD_DIR}/raspberrypi-kernel-headers_*.deb)

echo "::set-output name=filename_kernel::${FILENAME_KERNEL}"
echo "::set-output name=filename_headers::${FILENAME_HEADERS}"
